# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sebastian/Documents/tp4-grupal-7542-2c2017

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sebastian/Documents/tp4-grupal-7542-2c2017

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sebastian/Documents/tp4-grupal-7542-2c2017/CMakeFiles /home/sebastian/Documents/tp4-grupal-7542-2c2017/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sebastian/Documents/tp4-grupal-7542-2c2017/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

src/client/StartWindow.o: src/client/StartWindow.cpp.o

.PHONY : src/client/StartWindow.o

# target to build an object file
src/client/StartWindow.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/StartWindow.cpp.o
.PHONY : src/client/StartWindow.cpp.o

src/client/StartWindow.i: src/client/StartWindow.cpp.i

.PHONY : src/client/StartWindow.i

# target to preprocess a source file
src/client/StartWindow.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/StartWindow.cpp.i
.PHONY : src/client/StartWindow.cpp.i

src/client/StartWindow.s: src/client/StartWindow.cpp.s

.PHONY : src/client/StartWindow.s

# target to generate assembly for a file
src/client/StartWindow.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/StartWindow.cpp.s
.PHONY : src/client/StartWindow.cpp.s

src/client/main.o: src/client/main.cpp.o

.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i

.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s

.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/common/Socket.o: src/common/Socket.cpp.o

.PHONY : src/common/Socket.o

# target to build an object file
src/common/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/Socket.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Socket.cpp.o
.PHONY : src/common/Socket.cpp.o

src/common/Socket.i: src/common/Socket.cpp.i

.PHONY : src/common/Socket.i

# target to preprocess a source file
src/common/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/Socket.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Socket.cpp.i
.PHONY : src/common/Socket.cpp.i

src/common/Socket.s: src/common/Socket.cpp.s

.PHONY : src/common/Socket.s

# target to generate assembly for a file
src/common/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/Socket.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Socket.cpp.s
.PHONY : src/common/Socket.cpp.s

src/common/Thread.o: src/common/Thread.cpp.o

.PHONY : src/common/Thread.o

# target to build an object file
src/common/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/Thread.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Thread.cpp.o
.PHONY : src/common/Thread.cpp.o

src/common/Thread.i: src/common/Thread.cpp.i

.PHONY : src/common/Thread.i

# target to preprocess a source file
src/common/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/Thread.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Thread.cpp.i
.PHONY : src/common/Thread.cpp.i

src/common/Thread.s: src/common/Thread.cpp.s

.PHONY : src/common/Thread.s

# target to generate assembly for a file
src/common/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/common/Thread.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/common/Thread.cpp.s
.PHONY : src/common/Thread.cpp.s

src/server/ClientRequestHandler.o: src/server/ClientRequestHandler.cpp.o

.PHONY : src/server/ClientRequestHandler.o

# target to build an object file
src/server/ClientRequestHandler.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ClientRequestHandler.cpp.o
.PHONY : src/server/ClientRequestHandler.cpp.o

src/server/ClientRequestHandler.i: src/server/ClientRequestHandler.cpp.i

.PHONY : src/server/ClientRequestHandler.i

# target to preprocess a source file
src/server/ClientRequestHandler.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ClientRequestHandler.cpp.i
.PHONY : src/server/ClientRequestHandler.cpp.i

src/server/ClientRequestHandler.s: src/server/ClientRequestHandler.cpp.s

.PHONY : src/server/ClientRequestHandler.s

# target to generate assembly for a file
src/server/ClientRequestHandler.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/ClientRequestHandler.cpp.s
.PHONY : src/server/ClientRequestHandler.cpp.s

src/server/Listener.o: src/server/Listener.cpp.o

.PHONY : src/server/Listener.o

# target to build an object file
src/server/Listener.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Listener.cpp.o
.PHONY : src/server/Listener.cpp.o

src/server/Listener.i: src/server/Listener.cpp.i

.PHONY : src/server/Listener.i

# target to preprocess a source file
src/server/Listener.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Listener.cpp.i
.PHONY : src/server/Listener.cpp.i

src/server/Listener.s: src/server/Listener.cpp.s

.PHONY : src/server/Listener.s

# target to generate assembly for a file
src/server/Listener.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/Listener.cpp.s
.PHONY : src/server/Listener.cpp.s

src/server/main.o: src/server/main.cpp.o

.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i

.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s

.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... src/client/StartWindow.o"
	@echo "... src/client/StartWindow.i"
	@echo "... src/client/StartWindow.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/common/Socket.o"
	@echo "... src/common/Socket.i"
	@echo "... src/common/Socket.s"
	@echo "... src/common/Thread.o"
	@echo "... src/common/Thread.i"
	@echo "... src/common/Thread.s"
	@echo "... src/server/ClientRequestHandler.o"
	@echo "... src/server/ClientRequestHandler.i"
	@echo "... src/server/ClientRequestHandler.s"
	@echo "... src/server/Listener.o"
	@echo "... src/server/Listener.i"
	@echo "... src/server/Listener.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

