#ifndef TP4_TOWERDEFENSE_CONSTANTS_H
#define TP4_TOWERDEFENSE_CONSTANTS_H


enum ClientRequestsNonPlaying {
    CLIENT_REQUEST_ACCESS_GAME_MENU = 0,
    CLIENT_REQUEST_ACCESS_CONFIGURATION_MENU = 1,
    CLIENT_REQUEST_CREATE_NEW_GAME = 2,
    CLIENT_REQUEST_ENTER_EXISTING_GAME = 3
};

enum ClientRequestsPlaying {
    CLIENT_REQUEST_PUT_TOWER = 100
};

enum class ServerNotifications {
    SERVER_NOTIFICATION_PUT_TOWER = 200
};


#endif //TP4_TOWERDEFENSE_CONSTANTS_H
